# Goal
geometry_msgs/PoseStamped pose_target
bool cartesian_motion 0
bool relative_motion 0
float64 velocity_scaling 1.0

---
# Result
moveit_msgs/MoveItErrorCodes result

---
# Feedback
float32 progress
